const product = {
	active: true,
	assets: ['', ''],
	categories: [],
	checkout_url: { checkout: '', display: '' },
	collects: {
		fullname: true,
		shipping_address: true,
		billing_address: true,
		extrafields: false,
	},
	conditionals: {
		is_active: true,
		is_free: false,
		is_tax_exempt: false,
		is_pay_what_you_want: false,
		is_quantity_limited: true,
		collects_billing_address: true,
		collects_extrafields: false,
		collects_fullname: true,
		collects_shipping_address: true,
		has_digital_delivery: false,
		has_images: true,
		has_physical_delivery: true,
		has_rich_embed: false,
		has_video: false,
	},
	created: null,
	description: '',
	extrafields: [],
	has: {
		digital_delivery: false,
		physical_delivery: true,
		images: true,
		video: false,
		rich_embed: false,
	},
	id: '',
	is: {
		active: true,
		free: false,
		tax_exempt: false,
		pay_what_you_want: false,
		quantity_limited: true,
	},
	media: { type: '', source: '' },
	meta: null,
	name: '',
	permalink: '',
	price: {
		raw: null,
		formatted: '',
		formatted_with_symbol: '',
		formatted_with_code: '',
	},
	quantity: null,
	related_products: [],
	seo: { title: null, description: null },
	sku: null,
	sort_order: 0,
	thank_you_url: null,
	updated: null,
	variant_groups: [],
};

export default product;
